### ISSUE TITLE
multimaterial not working

### ISSUE THREAD

**Issue by code945** [jagenjo/collada.js#5]
```
 if(iMat == 0)
	node.material = matname;
else
{
	if(!node.materials)
		node.materials = [];
	node.materials.push(matname);
}
```
is that because this code only assign the first material to node material? how to fix this?

**Comment by code945** [comment]
i just find that there's a sub materials attribute in litescene/meshrender component. would you please give me some tips about how to use this feature? or any doc?
https://github.com/jagenjo/litescene.js/blob/master/src/components/meshRenderer.js#L44

**Comment by jagenjo** [comment]
multimaterial is not fully supported yet, there has been some proof of work done but due to the way the engine is organized (every node has only one material) is not easy to solve.

the solution is to split nodes with multiple materials into several nodes.
